fx_pipeline:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: currency-tracker-507607
      dataset: fx_marts
      threads: 4
      location: US
      priority: interactive
      impersonate_service_account: fx-pipeline-sa@currency-tracker-507607.iam.gserviceaccount.com